### ISSUE TITLE
Make plugin agnostic of integrations

### ISSUE THREAD

**Issue by XedinUnknown** [osDXP/osdxp-dashboard#15]
## The Problem
Currently, the plugin has checks for MultilingualPress [here][1] and [here][2]. This is wrong, because 3rd parties should be integrating with osDXP, not the other way around. osDXP is the platform for integrations. It cannot possibly know of all the other code that may want to integrate with it. Furthermore, the integration of 3rd parties should be controlled by those parties.

## Suggested Solution
1. Remove code that relates to 3rd-party integrations (not to dependencies of this project).
2. Introduce entrypoints that 3rd parties can use for integration. For example, add WP hooks.

[1]: https://github.com/osDXP/osdxp-dashboard/blob/master/templates/dashboard-actions-multisite-admin.php#L105-L122
[2]: https://github.com/osDXP/osdxp-dashboard/blob/master/templates/dashboard-actions-network-admin.php#L104-L121

**Comment by al-esc** [comment]
@iardeleanu @amuscalu tagging you for triage
