### ISSUE TITLE
Vendor code committed

### ISSUE THREAD

**Issue by XedinUnknown** [osDXP/osdxp-dashboard#16]
## The Problem
[Vendor code][vendor] seems to be committed to the repository. This is [wrong][1].

## Suggested Solution
Remove the `vendor` folder. Do not remove `composer.lock`. Include a build process in the form of instructions (e.g. explain how to build in the readme) or code (e.g. for Grunt, Phing, Ant, etc).

[1]: https://getcomposer.org/doc/faqs/should-i-commit-the-dependencies-in-my-vendor-directory.md
[vendor]: https://github.com/osDXP/osdxp-dashboard/tree/master/vendor

**Comment by al-esc** [comment]
fixed in release [1.0.1](https://github.com/osDXP/osdxp-dashboard/releases/tag/v1.0.1)
