### ISSUE TITLE
Unbuilt asset paths with WP_DEBUG on

### ISSUE THREAD

**Issue by XedinUnknown** [osDXP/osdxp-dashboard#46]
## The Problem
Currently, the plugin will use URLs and paths for unbuilt, i.e. source, assets, if `WP_DEBUG` is on. This is not always desirable, because developers may want to debug PHP with built assets: the build process or sources/assets may have problems of their own.

## Suggested Solution
Use the dedicated constant [`SCRIPT_DEBUG`][] to determine whether source assets should be used instead of built ones.

[`SCRIPT_DEBUG`]: https://wordpress.org/support/article/debugging-in-wordpress/#script_debug

**Comment by al-esc** [comment]
@iardeleanu @amuscalu tagging you for triage
