### ISSUE TITLE
Assets not registered unless used

### ISSUE THREAD

**Issue by XedinUnknown** [osDXP/osdxp-dashboard#47]
## The Problem
Currently, assets are only being registered at the same time as they are being used. This has several issues.

1. osDXP code will be forced to duplicate asset configuration if assets need to be enqueued conditionally in several different places.

2. Same problem with any 3rd-party modules or integrations: they cannot programmatically know or re-use existing osDXP asset configuration, and are forced to duplicate it.

Imagine a module or extension that needs to extend the existing configuration of `app.js`. Perhaps the module needs to additionally enqueue the JS for its own use on more pages than osDXP originally caters for. This module has to either duplicate the JS of osDXP's `app.js`, or duplicate the configuration of that asset, i.e. its URL, version, and dependency list.

## Possible Cause
Assets are registered (configured) and enqueued in the same place under the same conditions.

## Suggested Solution
1. Register the JS and CSS _unconditionally_ in a separate centralized location.
2. Enqueue the JS and CSS _conditionally_ only when necessary.

This would make their configuration re-usable, allowing other code (including 3rd-party) use or depend on those assets without duplicating them or their configuration.

**Comment by al-esc** [comment]
@iardeleanu @amuscalu tagging you for triage
