### ISSUE TITLE
Fatal error: Uncaught Error: Class 'OSDXP_Dashboard\OsdxpModuleUpdateChecker' not found

### ISSUE THREAD

**Issue by endurtech** [osDXP/osdxp-dashboard#51]
Fresh WP 5.2.4 install with PHP 7.2, MySQL 5.6, Apache

( ! ) Fatal error: Uncaught Error: Class 'OSDXP_Dashboard\OsdxpModuleUpdateChecker' not found in /app/public/wp-content/plugins/osdxp-dashboard-develop/includes/utils.php on line 31
( ! ) Error: Class 'OSDXP_Dashboard\OsdxpModuleUpdateChecker' not found in /app/public/wp-content/plugins/osdxp-dashboard-develop/includes/utils.php on line 31
Call Stack
No.	Time	Memory	Function	Location
1	0.0000	402456	{main}( )	.../plugins.php:0
2	0.0001	403128	require_once( '/app/public/wp-admin/admin.php' )	.../plugins.php:10
3	0.0001	403608	require_once( '/app/public/wp-load.php' )	.../admin.php:34
4	0.0001	404344	require_once( '/app/public/wp-config.php' )	.../wp-load.php:37
5	0.0001	411312	require_once( '/app/public/wp-settings.php' )	.../wp-config.php:76
6	0.0204	2809888	do_action( )	.../wp-settings.php:525
7	0.0204	2810264	WP_Hook->do_action( )	.../plugin.php:465
8	0.0204	2810264	WP_Hook->apply_filters( )	.../class-wp-hook.php:310
9	0.0536	3160528	OSDXP_Dashboard\hook_update_check( )	.../class-wp-hook.php:286
The site is experiencing technical difficulties. Please check your site admin email inbox for instructions.

![WordPress › Error](https://user-images.githubusercontent.com/47306715/68533991-a10a2700-02fd-11ea-8be9-86f9095db28e.jpg)

**Comment by al-esc** [comment]
Hi @endurtech, can you please let me know which installation method you have used?
If you're not using the release asset, have you already ran `composer install`? 
Thanks!

**Comment by endurtech** [comment]
Thanks for the prompt reply @al-esc 

I am running a local development environment created by localbyflywheel. I simply visited the Github page and downloaded the latest zip. Installed it as I would with any old WordPress plugin (via zip upload method).

I have not run the "composer install". Perhaps that is what I am missing. Sorry, I am new to all this and appreciate your patience and understanding along with your feedback and assistance.

Respectfully,
Manny R.

**Comment by al-esc** [comment]
You should be able to successfully install it by deleting the plugin and installing it again using [this](https://github.com/osDXP/osdxp-dashboard/releases/download/v1.0.3/osdxp-dashboard.zip) zip, v1.0.3 release asset. 
If you don't mind, please let me know if that fixes your problem. 
This is due to the fact that composer vendor dependencies are not included in the repo. More information on this subject is available [here](https://getcomposer.org/doc/faqs/should-i-commit-the-dependencies-in-my-vendor-directory.md). 
Cheers!

**Comment by endurtech** [comment]
You are correct @al-esc 

That fixed it.

The provided resource helped me to understand why it wasn't included. This will help me in the future no doubt as many (if not most) others will not include composer vendor dependencies.

Thank you again for your time and assistance!

Respectfully,
Manny R.
